"use client";
import { useState } from "react";
import styled from "styled-components";
import { AnimatePresence, motion } from "framer-motion";
import { PenTool, Palette, Code2, TrendingUp, ArrowRight, PackageCheck, type LucideIcon } from "lucide-react";
import { DISCIPLINAS, type DisciplinaId } from "@/domain/entities/Disciplina";

const ICONS:Record<DisciplinaId,LucideIcon>={copywriting:PenTool,"ux-ui":Palette,frontend:Code2,growth:TrendingUp};
const Wrap=styled.div`width:100%;max-width:1440px;margin:0 auto;`;
const Intro=styled.p`margin:-6px 0 18px;text-align:center;color:${({theme})=>theme.colors.foregroundMuted};font:600 clamp(1rem,1.5vw,1.25rem) ${({theme})=>theme.fonts.body};`;
const Nav=styled.nav`display:grid;grid-template-columns:repeat(4,1fr);gap:9px;margin-bottom:14px;@media(max-width:720px){grid-template-columns:repeat(2,1fr);}`;
const NavItem=styled.button<{$active:boolean}>`min-height:82px;display:flex;align-items:center;gap:13px;padding:16px 18px;border:1px solid ${({$active,theme})=>$active?theme.colors.accent:theme.colors.border};border-radius:${({theme})=>theme.radii.md};background:${({$active,theme})=>$active?theme.colors.accentMuted:theme.colors.backgroundElevated};color:white;cursor:pointer;text-align:left;font:800 clamp(1rem,1.5vw,1.35rem) ${({theme})=>theme.fonts.header};svg{color:${({$active,theme})=>$active?theme.colors.accent:theme.colors.foregroundMuted};}&:hover{border-color:${({theme})=>theme.colors.accent};}`;
const Stage=styled(motion.section)`position:relative;overflow:hidden;min-height:470px;display:grid;grid-template-columns:.95fr 1.05fr;gap:30px;padding:clamp(30px,4vw,58px);border:1px solid ${({theme})=>theme.colors.border};border-radius:${({theme})=>theme.radii.lg};background:radial-gradient(circle at 85% 10%,#3b0a18 0,transparent 35%),${({theme})=>theme.colors.backgroundElevated};@media(max-width:820px){grid-template-columns:1fr;}`;
const Hero=styled.div`position:relative;z-index:1;display:flex;flex-direction:column;justify-content:center;`;
const IconDisk=styled.div`width:92px;height:92px;display:grid;place-items:center;margin-bottom:22px;border-radius:50%;background:${({theme})=>theme.colors.accent};box-shadow:0 0 0 18px #ff1b441a;`;
const Number=styled.div`position:absolute;top:-42px;right:28px;color:#fff;font:900 clamp(12rem,25vw,25rem)/.8 ${({theme})=>theme.fonts.header};opacity:.035;`;
const Title=styled.h3`margin-bottom:12px;font:900 clamp(3.1rem,6vw,6.3rem)/.92 ${({theme})=>theme.fonts.header};letter-spacing:-.07em;`;
const Description=styled.p`max-width:650px;color:${({theme})=>theme.colors.foregroundMuted};font-size:clamp(1.25rem,2.1vw,1.75rem);line-height:1.35;`;
const Goal=styled.div`margin-top:26px;padding:15px 0 15px 18px;border-left:4px solid ${({theme})=>theme.colors.accent};font-size:clamp(1.1rem,1.7vw,1.4rem);b{color:${({theme})=>theme.colors.accent};}`;
const Work=styled.div`position:relative;z-index:1;display:grid;grid-template-columns:1fr 1fr;gap:13px;align-content:center;`;
const Card=styled.div`min-height:205px;padding:22px;border:1px solid ${({theme})=>theme.colors.border};border-radius:${({theme})=>theme.radii.md};background:#0a0a0acc;h4{display:flex;align-items:center;gap:8px;margin-bottom:16px;font:800 1.15rem ${({theme})=>theme.fonts.header};}ul{display:grid;gap:11px;list-style:none;}li{display:flex;gap:8px;color:${({theme})=>theme.colors.foregroundMuted};font-size:1rem;line-height:1.35;svg{flex:none;color:${({theme})=>theme.colors.accent};}}`;
const Question=styled.div`grid-column:1/-1;padding:17px 19px;border:1px dashed ${({theme})=>theme.colors.accent};border-radius:${({theme})=>theme.radii.md};color:${({theme})=>theme.colors.foregroundMuted};font-size:1.1rem;line-height:1.45;b{color:white;}`;

export function DisciplinasGrid(){const [active,setActive]=useState<DisciplinaId>(DISCIPLINAS[0].id);const d=DISCIPLINAS.find(x=>x.id===active)!;const Icon=ICONS[d.id];const number=DISCIPLINAS.findIndex(x=>x.id===d.id)+1;return <Wrap><Intro>La conversión no pertenece a una disciplina: aparece cuando estrategia, palabras, diseño y tecnología empujan en la misma dirección.</Intro><Nav role="tablist" aria-label="Disciplinas">{DISCIPLINAS.map(x=>{const I=ICONS[x.id];return <NavItem key={x.id} role="tab" aria-selected={active===x.id} $active={active===x.id} onClick={()=>setActive(x.id)}><I size={27}/>{x.nombre}</NavItem>})}</Nav><AnimatePresence mode="wait"><Stage key={d.id} initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-8}}><Number>0{number}</Number><Hero><IconDisk><Icon size={45}/></IconDisk><Title>{d.nombre}</Title><Description>{d.descripcion}</Description><Goal><b>Su misión:</b> {d.objetivo}</Goal></Hero><Work><Card><h4><ArrowRight size={19}/>Cómo aporta</h4><ul>{d.responsabilidades.map(x=><li key={x}><ArrowRight size={15}/>{x}</li>)}</ul></Card><Card><h4><PackageCheck size={19}/>Qué deja listo</h4><ul>{d.entregables.map(x=><li key={x}><ArrowRight size={15}/>{x}</li>)}</ul></Card><Question><b>La pregunta que protege su trabajo:</b> “{d.preguntaClave}”</Question></Work></Stage></AnimatePresence></Wrap>}
